In [2]:
# import numpy

In [3]:
a = np.array([1, 5, 3, 7, 9, 4, 10])


In [ ]:
# What shape (dimension) does the array have?




In [4]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])






In [15]:
# math




[ 6 10  8 12 25  9 15]
[ 0.5         1.66666667  3.          1.75        2.          0.57142857
 10.        ]


In [25]:
# math with build in functions






45
[ 6 15 24]
[12 15 18]
5.0


In [19]:
x = np.arange(15)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [8]:
# Open the "2018051011_pangaea.txt" textfile and read in the values using numpy! 
# data = np.genfromtxt()


TypeError: genfromtxt() missing 1 required positional argument: 'fname'

In [134]:
# Assign the column names to the extracted data for better readability.


[1.0000e+01 1.4000e+01 1.9000e+01 ... 3.0074e+04 3.0078e+04 3.0081e+04]
[ 7.6  7.7  7.9 ... 37.6 37.7 37.7]


In [135]:
def calculate_dewpoint(temperature, rh):


In [136]:
def calculate_wind_components(wdir, wspeed):


tau = calculate_dewpoint(temperature, rh)
u,v = get_components(dd*np.pi/180, ff)
tpot = (temperature + 273.15) * np.power(pressure[0]/pressure, 287/1005)

In [137]:
%matplotlib inline

In [6]:
import matplotlib.pyplot as plt
import matplotlib

















