#### 1.Write a NumPy program to print the NumPy version in your system. 

In [1]:
import numpy as np
np.__version__

'1.19.1'

#### 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [12]:
values = np.arange(2,11,1)
values.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])


   #### 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]



In [9]:
a = np.zeros((10))
a[6] = 11.
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

#### 5. Write a NumPy program to create an array with values ranging from 12 to 38. Expected Output: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [16]:
b = np.arange(12,38,1)
print(b)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]



#### 32. Write a NumPy program to save a NumPy array to a text file.



In [16]:
np.savetxt('out_file.txt', b)

['part1_basics.ipynb',
 'part4_netcdf.ipynb',
 'Tasks_Numpy.ipynb',
 '.ipynb_checkpoints',
 'Untitled2.ipynb',
 'part3_numpy_matplotlib.ipynb',
 'Tasks.ipynb',
 'part2_standardlib.ipynb',
 'Colormaps.py',
 'part0_check_if_setup_works.ipynb',
 'Untitled1.ipynb',
 'out_file.txt',
 'Untitled.ipynb',
 'data']

#### Write a NumPy program to find the memory size of a NumPy array. Expected Output: 128 bytes

In [17]:
print("%d bytes" % (b.size * b.itemsize))

208 bytes


#### Write a NumPy program to collapse a 3-D array into one dimension array. Expected Output: 3-D array: [[ 1. 0. 0.] [ 0. 1. 0.] [ 0. 0. 1.]] One dimension array: [ 1. 0. 0. 0. 1. 0. 0. 0. 1.]

In [41]:
array_3d = np.array([[ 1., 0., 0.], [ 0.,1., 0.], [ 0., 0., 1.]] )
print(array_3d)

array_3d = array_3d.flatten()
print(array_3d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]



   #### Write a NumPy program to concatenate two 2-dimensional arrays. Expected Output: Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]) Expected Output: [[ 0 1 3 0 2 4] [ 5 7 9 6 8 10]]



In [18]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

np.hstack((a, b))

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

### Write a NumPy program to create a NumPy array of 10 integers from a generator. 

In [24]:
generator_function = np.random.default_rng(seed=42)
generator_function.integers(1, 10, 10)

array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1])