## Part 3 - NumPy
### import numpy and give it an alias (alias: In Python alias are an alternate name for referring to the same thing.)

In [1]:
import numpy as np

### initialize a numpy array

In [2]:
arr = np.array(42)    # 0D array, aka. scalar
arr = np.array([1, 2, 3, 4, 5])    # 1D array, aka. vector
arr = np.array([[1, 2, 3], [4, 5, 6]])    # 2D array, aka. matrix
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])    # 3D array, aka. tensor


### What shape (dimension) does the array have?

In [3]:
print(f'arr =\n{arr}')
print(f'dimension of arr = {arr.ndim}')
print(f'shape(number of elements per dimension) of arr = {arr.shape}')


arr =
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension of arr = 3
shape(number of elements per dimension) of arr = (2, 2, 3)



### change the fifth element in the array to 20, note: python starts counting at 0!!

In [4]:
a = np.array([1, 5, 3, 7, 9])
a[4] = 20
print(a)


[ 1  5  3  7 20]


### initialize a matrix, and access elements

In [5]:
# input a list of lists with, the length of the most inner lists need to be the same! (e.g.: a rectangular matrix)
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(f'array b =\n{b}')    # print the array, ('\n' : new line keyword)
print(f'shape of array b = {b.shape}')    # look at the shape
print(f'b[0,0] = {b[0,0]}')    # access one value array[row_index, column_index],
print(f'second row b1_ = {b[1,:]}')    # access a whole row
print(f'third column b_2 = {b[:,2]}')    # access a whole colum



print(f'slice of b =\n{b[1:,:2]}')    # it is also possible to acces slices,
print(f'transpose of b =\n{b.T}')


array b =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of array b = (3, 3)
b[0,0] = 1
second row b1_ = [4 5 6]
third column b_2 = [3 6 9]
slice of b =
[[4 5]
 [7 8]]
transpose of b =
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### show elements larger than 5

In [6]:
# logical indexing also available, access all elements in a larger than 5
print(a[a>5])

[ 7 20]


### mathematical operations

In [7]:
print(a[2] + a [0])    # math with single elemnts
print(a + 5) # each element in a + 5
print(a + b[0, :]) # each element in a + first row of b
print(a / np.array([2,3,1,4,10])) # element-wise division

4
[ 6 10  8 12 25]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
# summation
print(np.sum(b))
print(np.sum(b, axis=1))
print(np.sum(b, axis=0))

In [ ]:
# other commom math functions 
print(np.mean(b))
print(np.exp(b))
print(np.log10(b))
print(np.sin(b))
print(np.sqrt(b))

### generate arrays

In [ ]:
# generate arrays, many more @ https://numpy.org/doc/stable/reference/routines.array-creation.html
x = np.arange(15)
print(x)

zero_mat = np.zeros((3, 4, 2))    # fill create a matrix containing zeros 
print(zero_mat)

fill_value_mat = np.full((3, 4, 2), fill_value=-999.0)    # create a matrix, with an arbitrary fill value
print(fill_value_mat)

### Reading data from a text file using NumPy. Open the "2018051011_pangaea.txt" textfile and read in the values using the function 'genfromtxt' (generates a numpy array from a text file)! 

In [ ]:
data_path = "data/2018051011_pangaea.txt"
data = np.genfromtxt(
    data_path,          # first arg: path of the file
    delimiter="\t",     # separator between numbers, '\t' = tab, '\n' 0 newline, ...
    skip_header=16      # skip first 16 lines in the textfile
)
print(data)
print(data.shape)

import datetime
dt = datetime.datetime.strptime(data_path[5:data_path.rfind('_')], "%Y%m%d%H")
print(f'date = {dt}')

### Assign the column names to the extracted data for better readability.

In [ ]:
altitude = data[:,0]
print(altitude)
pressure = data[:,1]
temperature = data[:,2]
rh = data[:,3]
dd = data[:,4]
ff = data[:,5]
print(f'relative humidity = {rh}')

### define function for dew point calculation

In [ ]:
def calculate_dewpoint(temperature, rh):
    Esaett = 6.107e2 * np.exp((17.08*temperature)/(234.2 + temperature))
    wvparpress = rh/100*Esaett
    tau = 234.2/((17.08/(np.log(wvparpress/6.107e2)))-1)
    return tau

### define function tocalculate wind components

In [ ]:
def calculate_wind_components(wdir, wspeed):
    u = -wspeed * np.sin(wdir)
    v = -wspeed * np.cos(wdir)
    return u, v


# calculate wind components and potential temperature
tau = calculate_dewpoint(temperature, rh)
u,v = calculate_wind_components(dd*np.pi/180, ff)
tpot = (temperature + 273.15) * np.power(pressure[0]/pressure, 287/1005)

## Part 3 - Matplotlib
### import numpy and give it an alias (alias: In Python alias are an alternate name for referring to the same thing.)



In [ ]:
import matplotlib.pyplot as plt
import matplotlib
# this line necessary for jupyter notebooks visualization
%matplotlib inline    


In [ ]:
# open a figure
fig, ax = plt.subplots(1, figsize=(5,5.7))

# line plot to axis 'ax'
ax.plot(tau, altitude, color='blue', label='dew point')
# second line plot to axis 'ax'
ax.plot(temperature, altitude, color='red', label='T')

# define x and y axis limits
ax.set_ylim([0,11000])
ax.set_xlim([-70,20])

# change appearance of the axis ticks
ax.xaxis.set_major_locator(matplotlib.ticker.MultipleLocator(20))
ax.xaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(4))
ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(2))
ax.tick_params(axis='both', which='major', labelsize=14, width=2, length=4.5, right=True, top=True)
ax.tick_params(axis='both', which='minor', labelsize=14, width=1.5, length=2.5, right=True, top=True)

# define axis labels
ax.set_xlabel('Temperature [$^{\circ}$C]', fontweight='semibold', fontsize=15)
ax.set_ylabel('Height [m]', fontweight='semibold', fontsize=15)

# plot a legend
ax.legend()

# tight_layout automatically adjusts subplot parameters so that the subplot(s) 
# fits in to the figure area. This is an experimental feature and may not 
# work for some cases. It only checks the extents of ticklabels, axis labels, and titles.
plt.tight_layout()

# save the plot to a file
savename = f'{dt:%Y%m%d_%H%M}_profile_t.png'
fig.savefig(savename, dpi=250)



In [ ]:
fig, ax = plt.subplots(1, figsize=(5,5.7))

ax.plot(tpot, altitude, color='darkgreen', label='pot. temperature')

barb_x_loc = np.ones(altitude.shape)*285
ax.barbs(barb_x_loc[::100], altitude[::100], u[::100], v[::100], 
         pivot='middle', length=7)

ax.set_ylim([0,11000])
ax.set_xlim([280,335])

ax.xaxis.set_major_locator(matplotlib.ticker.MultipleLocator(10))
ax.xaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(2))
ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(2))
ax.set_xlabel('pot. Temp [K]', fontweight='semibold', fontsize=15)
ax.set_ylabel('Height [m]', fontweight='semibold', fontsize=15)
ax.legend(fontsize=13, bbox_to_anchor=(0.2,0.9,0.9,0.102))

ax.tick_params(axis='both', which='major', labelsize=14,
               width=2, length=4.5, right=True, top=True)
ax.tick_params(axis='both', which='minor', labelsize=14,
               width=1.5, length=2.5, right=True, top=True)

plt.tight_layout()
#savename = '{}_profile_tpot_wind.png'.format(dt.strftime('%Y%m%d_%H%M'))
#fig.savefig(savename, dpi=250)